/* ============================================================
   PHASE 4: REVENUE ANALYSIS
   PROJECT: RETAIL CUSTOMER INSIGHTS
   ============================================================ */


/* ------------------------------------------------------------
   Question 1:
   Which product categories generate the most revenue?
   ------------------------------------------------------------ */

SELECT
    Category,
    SUM(Purchase_Amount_USD) AS Revenue
FROM retail_customer_insights
GROUP BY Category
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Question 2:
   Which season generates the highest revenue?
   ------------------------------------------------------------ */

SELECT
    Season,
    SUM(Purchase_Amount_USD) AS Revenue
FROM retail_customer_insights
GROUP BY Season
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Question 3:
   How much revenue is generated by each gender?
   ------------------------------------------------------------ */

SELECT
    Gender,
    SUM(Purchase_Amount_USD) AS Revenue
FROM retail_customer_insights
GROUP BY Gender
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Question 4:
   Which locations contribute the most revenue?
   ------------------------------------------------------------ */

SELECT
    Location,
    SUM(Purchase_Amount_USD) AS Revenue
FROM retail_customer_insights
GROUP BY Location
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Question 5:
   Do subscribers generate more revenue than non-subscribers?
   ------------------------------------------------------------ */

SELECT
    Subscription_Status,
    SUM(Purchase_Amount_USD) AS Revenue
FROM retail_customer_insights
GROUP BY Subscription_Status
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Question 6:
   Does offering discounts increase revenue?
   ------------------------------------------------------------ */

SELECT
    Discount_Applied,
    SUM(Purchase_Amount_USD) AS Revenue
FROM retail_customer_insights
GROUP BY Discount_Applied
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Question 7:
   Which payment method generates the most revenue?
   ------------------------------------------------------------ */

SELECT
    Payment_Method,
    SUM(Purchase_Amount_USD) AS Revenue
FROM retail_customer_insights
GROUP BY Payment_Method
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Question 8:
   Which shipping type is associated with the highest revenue?
   ------------------------------------------------------------ */

SELECT
    Shipping_Type,
    SUM(Purchase_Amount_USD) AS Revenue
FROM retail_customer_insights
GROUP BY Shipping_Type
ORDER BY Revenue DESC;


/* ------------------------------------------------------------
   Question 9:
   What is the average revenue generated per category?
   ------------------------------------------------------------ */

SELECT
    Category,
    ROUND(AVG(Purchase_Amount_USD),2) AS Avg_Revenue
FROM retail_customer_insights
GROUP BY Category
ORDER BY Avg_Revenue DESC;


/* ------------------------------------------------------------
   Question 10:
   Which category performs best during each season?
   ------------------------------------------------------------ */

SELECT
    Season,
    Category,
    SUM(Purchase_Amount_USD) AS Revenue
FROM retail_customer_insights
GROUP BY Season, Category
ORDER BY Season, Revenue DESC;


/* ============================================================

Revenue Analysis Summary
* The business generated a total revenue of $233,081, with Clothing emerging as the highest revenue-generating category, contributing $104,264.
* Fall was the best-performing season, generating $60,018 in revenue, closely followed by Winter and Spring.
* Male customers contributed significantly more revenue ($157,890) than female customers ($75,191).
* Montana was the top-performing location, generating $5,784 in revenue.
* Non-subscribers generated the majority of revenue ($170,436), while subscribers contributed $62,645, indicating potential opportunities to improve subscription adoption.
* Purchases made without discounts generated more revenue ($133,670) than discounted purchases ($99,411).
* Revenue was fairly evenly distributed across payment methods, with Credit Card and PayPal generating the highest revenue.
* Free Shipping was the most profitable shipping option, generating $40,777 in revenue.
* Although Footwear had the highest average purchase value ($60.26), Clothing remained the strongest category overall due to its higher sales volume.
* Across all seasons, Clothing consistently generated the highest revenue, making it the key driver of overall business performance.

   ============================================================ */